---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim-<<YAML_NUMERIC_HASH_OF_HOST_AND_PORT>>
  namespace: <<YAML_NAMESPACE>>
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc #The name we have for our StorageClass
  resources: 
    requests:
      storage: 1Gi #This is the minimum as per EBS policy
---