---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer #Provision only after first PVC claim
parameters:
  tagSpecification_1: "pvcname={{ .PVCName }}"
  tagSpecification_2: "pvname={{ .PVName }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: <<YAML_DB_SCHEMA_NAME>>-dbcreation-script
  namespace: <<YAML_NAMESPACE>>
data:
  init-script.sql: |-
    CREATE DATABASE IF NOT EXISTS <<YAML_DB_SCHEMA_NAME>>;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: <<YAML_DB_SCHEMA_NAME>>-db-auth-config-script
  namespace: <<YAML_NAMESPACE>>
data:
  default_auth: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    key_buffer_size=1M
    max_allowed_packet=1M
    thread_stack=200K
    thread_cache_size=8
    max_connect_errors=100
    max_connections=100
    binlog_cache_size=1M
    net_buffer_length=1M
    default_storage_engine=InnoDB
    innodb_buffer_pool_instances=1#Use1instanceper1GBofInnoDBpoolsize
    innodb_buffer_pool_size=100M
    innodb_file_per_table=1
    innodb_flush_log_at_trx_commit=0
    innodb_flush_method=O_DIRECT
    innodb_log_buffer_size=16M
    innodb_log_file_size=16M
    innodb_stats_on_metadata=0
    innodb_read_io_threads=40
    innodb_write_io_threads=40
    innodb_buffer_pool_chunk_size=10
    innodb_lock_wait_timeout=600
    innodb_flush_log_at_trx_commit=1
    innodb_io_capacity=3000
    innodb_io_capacity_max=4000
    innodb_buffer_pool_dump_pct=80
    innodb_flush_neighbors=0
    innodb_doublewrite=0
    innodb_change_buffer_max_size=10
    innodb_old_blocks_pct=70
    innodb_old_blocks_time=5000
    innodb_use_native_aio=ON
    interactive_timeout=600
    wait_timeout=600
    net_read_timeout=300
    net_write_timeout=300
    connect_timeout=1800
    table_definition_cache=1K
    table_open_cache=2K
    table_open_cache=2K
    open_files_limit=4000
    max_heap_table_size=100M
    tmp_table_size=100M
    join_buffer_size=256K
    read_buffer_size=256K
    read_rnd_buffer_size=256K
    sort_buffer_size=128K
    performance_schema=ON
---

